"""added spotify_token to User

Revision ID: 02cbc6bd0e7f
Revises: 899674bdf2bf
Create Date: 2022-07-09 21:51:02.176619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cbc6bd0e7f'
down_revision = '899674bdf2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spotify_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spotify_token')
    # ### end Alembic commands ###
