"""added token to user

Revision ID: 899674bdf2bf
Revises: bda673efb7f5
Create Date: 2022-07-09 19:54:54.410293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899674bdf2bf'
down_revision = 'bda673efb7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('yandex_token', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'yandex_token')
    # ### end Alembic commands ###
