"""added yandex_token io user

Revision ID: bda673efb7f5
Revises:
Create Date: 2022-07-09 19:35:48.401497

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bda673efb7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('yandex_token', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'yandex_token')
    # ### end Alembic commands ###
