name: Python Pylin GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Running docker
      run: |
        docker build . --file Dockerfile
        docker-compose up
    - name: Running tests
      run: |
        python -m pytest
